# Generated by Django 4.0.3 on 2022-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_youtuber_crew_alter_youtuber_camera_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
